services:
  vault:
    image: vault:1.13.3
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=roottoken
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
