project:
  name: str(default=dekick,required=true)
  group: str(default=,required=false)
  artifacts:
    - path: str(default=,required=false)
  providers:
    credentials:
      driver: str(default=,required=false)
  environments:
    - name: str(default=test,required=true)
gitlab:
  url: str(default=,required=false)
  getenv: bool(default=false,required=false)
dekick:
  auto_update: bool(default=true,required=false)
  boilerplate: str(default=express,required=true)
  ports:
    - service: str(default=api,required=false)
      port: int(default=3000,required=false)
  flavour: str(default=express,required=true)
  settings:
    apidoc:
      generate: bool(default=false,required=false)
      legacy: bool(default=false,required=false)
    vite:
      enabled: bool(default=false,required=false)
