#!/usr/bin/env bash

unset DEKICK_PATH
unset PROJECT_ROOT

DEKICKRC_FILE=".dekickrc.yml"

if [ -n "$ZSH_VERSION" ]; then
  SHELL=zsh
elif [ -n "$BASH_VERSION" ]; then
  SHELL=bash
fi

function realpath() {
  local previouspwd=$PWD
  cd "$(dirname "$1")" || exit 1

  local link
  link=$(readlink "$(basename "$1")")

  while [ "$link" ]; do
    cd "$(dirname "$link")" || exit 1
    link=$(readlink "$(basename "$1")")
  done

  local realpath
  realpath="$PWD/$(basename "$1")"
  cd "$previouspwd" || exit 1

  echo "$realpath"
}

function show_banner() {
  if tty > /dev/null 2>&1; then
    local dekick_version
    dekick_version=$(cat "${DEKICK_PATH}/.version")

    echo 
    echo ' ______   _______  _       _________ _______  _       ';
    echo '(  __  \ (  ____ \| \    /\\__   ___/(  ____ \| \    /\\';
    echo '| (  \  )| (    \/|  \  / /   ) (   | (    \/|  \  / /';
    echo '| |   ) || (__    |  (_/ /    | |   | |      |  (_/ / ';
    echo '| |   ) || (      |  ( \ \    | |   | |      |  ( \ \ ';
    echo '| (__/  )| (____/\|  /  \ \___) (___| (____/\|  /  \ \';
    echo '(______/ (_______/|_/    \/\_______/(_______/|_/    \/';
    echo '                                                      ';    
    echo "${dekick_version} installed!"

    echo
    if [ "$PROJECT_ROOT" ]; then
      echo "Project path: ${PROJECT_ROOT}"
    fi
    echo "DeKick path: ${DEKICK_PATH}"
    echo
    echo "See help by running 'dekick --help'. Happy coding!"
  fi
}

function check_dekickrc() {
  if [[ ! -t 1 ]]; then
    return 0
  fi

  if [ "${PROJECT_ROOT}" = "${DEKICK_PATH}" ]; then
    return 0
  fi
  if [[ -t 1 ]] && [ ! -f "${PROJECT_ROOT}/${DEKICKRC_FILE}" ]; then
    echo -e "\n\033[33mWarning:\033[0m No ${DEKICKRC_FILE} file found in current directory."
    echo -ne "\nDo you want to start project creator in the current directory? (Y/n) "
    read -r answer
    if [ "$answer" = "${answer#[nN]}" ]; then
      dekick creator
    fi
    return 0
  fi
}

function check_test_mode() {
  if [[ ! -t 1 ]]; then
    return 0
  fi

  if [ "$PROJECT_ROOT" != "$DEKICK_PATH" ]; then
    return 0
  fi

  local dekick_version
  dekick_version=$(cat "${DEKICK_PATH}/.version")

  echo -e "\n\033[38;5;231;48;5;196m${dekick_version} in test mode installed\033[0m"
  echo -ne "\nDo you want to start tests using PyTest? (Y/n) "
  read -r answer

  if [ "$answer" = "${answer#[nN]}" ]; then
    HOST_PLATFORM=$(uname -s)
    PYTEST_ARGS=""

    if [ "${HOST_PLATFORM}" = "Linux" ]; then
      PYTEST_ARGS="-n6"
    fi

    dekick pytest ${PYTEST_ARGS}
  fi
  return 0
}

function dekick() {
  local PREV_PWD=$PWD
  cd "$PROJECT_ROOT" || exit 1
  "${DEKICK_PATH}/dekick-docker.sh" "$@"
  local EC=$?
  cd "$PREV_PWD" || exit 1
  return $EC
}

function dck() {
  dekick "$@"
}

# Checking if Docker daemon is running and there are proper rights to access it
if ! docker ps >/dev/null 2>&1; then
  echo "Docker daemon is not running or you don't have rights to access it."
  echo "DeKick will not work properly without Docker!"
fi


if [ -z "$DEKICK_PATH" ]; then
  if [ "$SHELL" = "zsh" ]; then
    SOURCE=${(%):-%N}
  elif [ "$SHELL" = "bash" ]; then
    SOURCE=${BASH_SOURCE[0]}
  fi

  if [ "$SOURCE" = "dev" ]; then
    DEKICK_PATH=$(realpath "$(pwd)")
  else
    DEKICK_PATH=$(realpath "$(dirname "${SOURCE}")")
  fi
fi

if [ -z "$PROJECT_ROOT" ]; then
  PROJECT_ROOT=$(realpath "$(pwd)")
fi

export DEKICK_PATH PROJECT_ROOT

show_banner
check_dekickrc
check_test_mode
