project:
  name: type="str",default="dekick",validation="name()",required="true"
  group: type="str",default="",validation="name()",required="false"
  artifacts: type="list",default="[{'path':'vendor/'}]",validation="{'path':'rel_path()'}",required="false"
  providers:
    credentials:
      driver: type="str",default="",validation="credentials_driver()",required="false"
  environments: type="list",default="[{'name':'test'},{'name':'beta'},{'name':'production'}]",validation="{'name':'name()'}",required="false"
  dotenv:
    ignore_keys: type="list",default="['PM_MAX_SPARE_SERVERS','PM_MIN_SPARE_SERVERS','PM_START_SERVERS','PM_MAX_CHILDREN','PM_MAX_REQUESTS','OPCACHE_VALIDATE_TIMESTAMPS']",validation="any()",required="false"
gitlab:
  url: type="str",default="",validation="url()",required="false"
  getenv: type="bool",default="false",validation="bool()",required="false"
hashicorp_vault:
  url: type="str",default="",validation="url()",required="false"
  mount_point: type="str",default="dekick",validation="rel_path()",required="false"
  auto_token_renewal: type="bool",default="true",validation="bool()",required="false"
dekick:
  auto_update: type="bool",default="true",validation="bool()",required="false"
  boilerplate: type="str",default="express/default",validation="boilerplate()",required="false"
  ports: type="list",default="[{'port':8080,'service':'web'},{'port':5432,'service':'db'},{'port':1080,'service':'mail'}]",validation="{'port':'port()','service':'name()'}",required="false"
  flavour: type="str",default="react",validation="flavour()",required="true"
  settings:
    apidoc:
      generate: type="bool",default="false",validation="bool()",required="false"
      legacy: type="bool",default="false",validation="bool()",required="false"
    seed:
      local: type="bool",default="true",validation="bool()",required="false"
